### PR TITLE
ipynb filter

### PR DESCRIPTION
**Pull request by benjaminum**
Filter for stripping output cells of ipynb files on commit.
Would this be OK as an alternative or in addition to the scripts?

### CODE REVIEW

**Comment by griegler** [comment]
Looks good to me, but we should mention somewhere in the docs that `nbconvert` is required?

**Comment by benjaminum** [comment]
Added a note that jupyter is required. That should be enough? Is nbconvert a separate package?

**Comment by griegler** [comment]
I think nbconvert is a separate package: https://nbconvert.readthedocs.io/en/latest/install.html

**Comment by benjaminum** [comment]
OK, added nbconvert.

**Review by griegler — APPROVED** [review]

**Pull request merged**
